version: "3.7"

services:
  postgres:
    image: postgres:16-alpine3.19
    restart: always
    ports:
      - "172.17.0.1:5432:5432"
    env_file:
      - .env

  admin:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
