"""playlist table

Revision ID: 51c4135bf82a
Revises: 0da4f2f72b0f
Create Date: 2024-03-26 22:35:25.314429

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "51c4135bf82a"
down_revision: Union[str, None] = "0da4f2f72b0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlist",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("owner", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playlist_sound",
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("sound_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlist.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sound_id"], ["sound.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("playlist_id", "sound_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playlist_sound")
    op.drop_table("playlist")
    # ### end Alembic commands ###
